### ISSUE TITLE
Panic: No source files found in ./example/hello (./example/hello)

### ISSUE THREAD

**Issue by ghost** [DQNEO/babygo#121]
I cloned the repo and ran:
```sh
go build -o babygo
``` 
and then
```sh
./babygo build -o hello ./example/hello
``` 
but it gave an error
```
panic: No source files found in ./example/hello (./example/hello)

goroutine 1 [running]:
......... 
```
i also tried running
```sh
./babygo build -o hello ./example/
```
and i got
```
panic: No source files found in /home/shour/go/src/github.com/DQNEO/babygo/src/os (os)
```
I am using Fedora linux
Thanks,
shour

**Comment by w-A-L-L-e** [comment]
Exact same issue in ubuntu 22.04:
```
./babygo build -o hello ./example/hello.go 
panic: No source files found in ./example/hello.go (./example/hello.go)

goroutine 1 [running]:
github.com/DQNEO/babygo/internal/builder.(*Builder).getPackageSourceFiles(0xc000137918?, {0x7ffd4cc42bec, 0x12})
	/home/wschrep/cppWork/babygo/internal/builder/builder.go:225 +0xad
github.com/DQNEO/babygo/internal/builder.(*Builder).ListDepth(0xc000137f00, {0x13?, 0x242?}, {0x7ffd4cc42bec, 0x12}, 0xc000114030)
	/home/wschrep/cppWork/babygo/internal/builder/builder.go:302 +0xb8
github.com/DQNEO/babygo/internal/builder.(*Builder).Build(0xc000137f00, {0x7ffd4cc42bd4, 0x8}, {0x500421, 0xe}, {0x7ffd4cc42be6, 0x5}, {0x7ffd4cc42bec, 0x12}, 0x0)
	/home/wschrep/cppWork/babygo/internal/builder/builder.go:49 +0x285
main.main()
	/home/wschrep/cppWork/babygo/main.go:72 +0x3b7
```
