### ISSUE TITLE
Hello World panics

### ISSUE THREAD

**Issue by prologic** [DQNEO/babygo#90]
```console
$ ./babygo example/hello.go
panic: main.QualifiedIdent("os.Stdout Not found in ExportedQualifiedIdents")

goroutine 1 [running]:
main.lookupForeignIdent(...)
	/Users/prologic/babygo/main.go:3818
main.getTypeOfExpr({0x10ab900?, 0xc0000ac108})
	/Users/prologic/babygo/main.go:2841 +0x1139
main.emitFuncall({0x10ab900?, 0xc0000ac138?}, {0xc000097070?, 0x1, 0x1}, 0x0?)
	/Users/prologic/babygo/main.go:914 +0x325
main.emitCallExpr(0xc000098ba0, 0x10c41fa?)
	/Users/prologic/babygo/main.go:1043 +0xee
main.emitExpr({0x10ab200?, 0xc000098ba0?}, 0x1077dba?)
	/Users/prologic/babygo/main.go:1437 +0x259
main.emitExprStmt(...)
	/Users/prologic/babygo/main.go:1808
main.emitStmt({0x10ab3c0?, 0xc000097120?})
	/Users/prologic/babygo/main.go:2406 +0x23d
main.emitFuncDecl({0xc0000a2350, 0x4}, 0xc0000d2000)
	/Users/prologic/babygo/main.go:2474 +0x3a5
main.generateCode(0xc0000c2240)
	/Users/prologic/babygo/main.go:2661 +0x629
main.buildPackage(0xc0000c2240, 0xc0000d1db0)
	/Users/prologic/babygo/main.go:4407 +0x2f7
main.main()
	/Users/prologic/babygo/main.go:4487 +0x79a
```

**Comment by DQNEO** [comment]
Could provide more info ? like OS, CPU , output of `go env` etc.

**Comment by DQNEO** [comment]
@prologic Thank you for reporting.
Could you provide more info ? like OS, CPU , output of `go env` etc.

**Comment by DQNEO** [comment]
Could you try using docker ? Like in the README  (I've just updated)

```
$ docker pull dqneo/ubuntu-compiler-go
$ ./docker-run
```

**Comment by prologic** [comment]
Ahh I see. I missed the point that it was Linux x86_64 only. It works in Docker 👌
